packages:
  - 'apps/*'
  - 'packages/*'
allowBuilds:
  '@firebase/util': false
  core-js: true
  esbuild: true
  protobufjs: false
  vue-demi: true
minimumReleaseAgeExclude:
  - '@unhead/bundler@3.3.2'
  - '@unhead/vue@3.3.2'
  - unhead@3.3.2
